# Generated by Django 5.1.1 on 2024-09-28 09:25

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content_type',
            new_name='file_type',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('file_name', 'file_type', 'by', 'semester')},
        ),
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(default=1, upload_to=main.models.content_file_name),
            preserve_default=False,
        ),
    ]
